alias capsescape='setxkbmap -option caps:escape'
alias vibashaliases='vim ~/dotfiles/.bash_aliases'
alias grepaliases='cat ~/dotfiles/.bash_aliases ~/.bash_aliases ~/.bash_privatealiases | grep'
alias ripgrep='rg'
alias setclip='xclip -selection c'
alias getclip='xclip -selection c -o'
alias pubip='dig +short myip.opendns.com @resolver1.opendns.com'
alias sln='ln --symbolic'
alias tmuxd='tmux detach'
alias LS='sl'
alias pingg='ping google.com'
alias tmuxa='tmux attach'
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias .4='cd ../../../../'
alias .5='cd ../../../../..'
alias supac='sudo pacman -S'
alias ls='ls -F --color=auto --group-directories-first'
alias ll='ls -la -F --color=auto --group-directories-first'
alias la='ls -a -F --color=auto --group-directories-first'
alias l.='ls -d .* -F --color=auto --group-directories-first'
alias vibashrc='vim ~/.bashrc'
alias vi3config='vim ~/.config/i3/config'
alias sysupdate='sudo pacman -Syu'
alias resetwal='wal -a 70 -i $(find ~/Pictures/wallpapers/ | shuf -n 1)'
alias resetwal2='wal -a 70 -i $(find ~/Pictures/wallpapers2/ | shuf -n 1)'
alias setwal='sudo wal -i'
alias rm='rm -i'
